#!/bin/sh
# remove-ext.sh
# Remove file extension to all files in current directory.
# Author: Jose Pablo Barrantes <xjpablobrx@gmail.com>
# Version: 0.1.0 Created: 07 Feb 2011

for f in *; do
    base=`basename $f .$ori`
    mv $f $base
    done
ls -la .