#!/usr/bin/env bash
# Common aliases
alias o='gnome-open . &'
alias more='less'
alias l='less'
alias chx='chmod +x'
alias k9="kill -9"
alias ct='cheat_fu'
alias ctr='cd ~/.cheats_fu_sheets && ronn -r *.1.ronn && cd -'
alias r*='rm -frv *'
alias mkd='mkdir -pv'
alias ..='cd ..'
alias g='git'
alias gst='git status'
alias sjp='$SHELL ~/.tmuxinator/jpablobr.tmux'
alias th=thunar
alias disable-touchpad='xinput --set-prop "ImPS/2 ALPS GlidePoint" "Device Enabled" 0'
alias enable-touchpad='xinput --set-prop "ImPS/2 ALPS GlidePoint" "Device Enabled" 1'
alias load-xresources='xrdb -merge ~/.Xresources'
alias hup='kill -HUP \!*'
alias j='jobs -l'
alias zombies='ps al | grep " Z "'
alias cpf='cp -frpv'
alias tmux='tmux -2'
alias aliasr="alias | egrep '(ruby|rails)' | cat | sed s:=:'$(tput setaf 5)=$(tput op)':g"
alias ag='alias | grep '
alias export-current-dir='export PATH="$PATH:`pwd`"'
add-apt-pkg-to-setup(){ echo "$1" >> ~/.private/setup/apt-get/apt-pkgs.dump; }
alias gnome2-set-emacs-interface='gconftool-2 --set /desktop/gnome/interface/gtk_key_theme Emacs --type string'
alias gnome3-set-emacs-interface='gsettings set org.gnome.desktop.interface gtk-key-theme Emacs'
# Show history
alias history='fc -l 1'
alias hi='history | tail -20'
alias r='fc -s'
alias whereami='echo "$( hostname --fqdn ) ($(hostname -i)):$( pwd )"'
# Emacs
alias es='emacs -nw'
alias ec='emacsclient -n'
alias e='emacsclient -c'
alias emm='emacs -nw -l ~/.emacs.d/inits/min-init.el'
alias em='emacs -Q -nw -l ~/.emacs.d/inits/jpablobr-init.el'
alias emr='emacs -nw  -l ~/.emacs.d/inits/ruby-init.el .'
alias emp='emacs -Q -nw -l ~/.emacs.d/inits/php-init.el'
alias empg='emacs -l ~/.emacs.d/inits/php-init.el . &'
alias emrg='emacs -l ~/.emacs.d/inits/ruby-init.el . &'
alias se='sudo emacs -nw -l ~/.emacs.d/inits/min-init.el'
# Pids IPs
alias pidips='sudo lsof -iTCP -sTCP:LISTEN -P'
# disk usage with human sizes and minimal depth
alias du1='du -h --max-depth=1'
alias fn='find . -name'
 # ANSI color chart
alias ansi-chart='for f in {30..37};do for b in {40..47};do printf "\e[%dm\e[%dm%d on %d\e[0m" $b $f $f $b;done;echo;done'
alias hgrep='history | grep $1'
op(){ "$1" >/dev/null 2>&1 & }
alias sloc='cloc --by-file-by-lang --exclude-dir .git'
alias curlr='curl -C - -L -O'

##############################################################################->
# - List
alias ls='ls -F --color=auto'
alias lsg='ls -lhGt'
alias lh="ls -lh"
alias lt='ls -lt'
alias la='ls -lah --format=long'
alias l-dir='ls --format=vertical'
alias l-recent='ls -lAt | head'
alias l-old='ls -lAt | tail'
alias ll='/bin/ls -lasi'
alias lll='/bin/ls -saild'
alias lsd='ls -d .[0-9a-zA-Z]*'
lg() { ls -la | grep "$1"; }

##############################################################################->
# - Ruby
alias rg='bundle exec rake -T | grep'
alias bl='bundle --local || bundle'

# - Rails
alias rr-asl='rails s >& log/server-`date +%Y-%m-%d-%H:%M`.log'
alias rr-adbm='rake db:migrate && rake db:test:prepare'
alias rr-routes='bundle exec rake routes > routes.txt'
alias rr-log='tail -fn0 ./log/*.log /var/log/apache*/*log'
alias rrc='pry -r ./config/environment'

# - heroku
alias h='heroku'
alias hi='heroku info'
alias hp="git push heroku master"
alias h-t='heroku logs --tail'
