#!/usr/bin/env bash
# Common aliases
alias o='open . &'
alias more='less'
alias l='less'
alias chx='chmod +x'
alias reload='. ~/.bash_profile'
alias open="gnome-open"
alias cl='clear'
alias _='sudo'
alias k9="kill -9"
alias mk_testd='cd ~/tmp && mkdir whatever && cd whatever'
alias ct='cheat_fu'
alias ctr='cd ~/.cheats_fu_sheets && ronn -r *.1.ronn && cd -'
alias srm='sudo rm'
alias rd='rm -rfv'
alias r*='rm -frv *'
alias mkd='mkdir -pv'
alias ..='cd ..'
alias g='git'
alias gst='git status'
alias sjp='$SHELL ~/.tmuxinator/jpablobr.tmux'
alias th=thunar
alias disable-touchpad='xinput --set-prop "ImPS/2 ALPS GlidePoint" "Device Enabled" 0'
alias enable-touchpad='xinput --set-prop "ImPS/2 ALPS GlidePoint" "Device Enabled" 1'
alias load-xresources='xrdb -merge ~/.Xresources'
alias ?=man
alias chars='wc -c'
alias hup='kill -HUP \!*'
alias j='jobs -l'
alias lines='wc -l'
alias rehash='hash -r'
alias Rsync='rsync -e ssh -auzv'
alias words='wc -w'
alias z=suspend
alias zombies='ps al | grep " Z "'
alias cpf='cp -frpv'
alias tmux='tmux -2'
alias aliasr="alias | egrep '(ruby|rails)' | cat | sed s:=:'$(tput setaf 5)=$(tput op)':g"
alias ag='alias | grep '
alias export-current-dir='export PATH="$PATH:`pwd`"'
add-apt-pkg-to-setup(){ echo "$1" >> ~/.private/setup/apt-get/apt-pkgs.dump; }
alias ruby='ruby -w'
alias gnome-set-emacs-interface='gconftool-2 --set /desktop/gnome/interface/gtk_key_theme Emacs --type string'
# Show history
alias history='fc -l 1'
alias hi='history | tail -20'
alias r='fc -s' # Awesome!
alias whereami='echo "$( hostname --fqdn ) ($(hostname -i)):$( pwd )"'
# Emacs
alias ec='emacsclient -cnw'
alias es='emacs -nw'
alias se='sudo emacs -nw -l ~/.emacs.d/jpablobr/min-init.el'
alias e='emacs -nw -l ~/.emacs.d/jpablobr/min-init.el'
alias em='emacs -l ~/.emacs.d/jpablobr/jpablobr-init.el &'
alias emnw='emacs -nw -l ~/.emacs.d/jpablobr/jpablobr-init.el'
alias emrnw='emacs -nw  -l ~/.emacs.d/jpablobr/ruby-init.el .'
alias emp='emacs -l ~/.emacs.d/jpablobr/php-init.el . &'
alias emr='emacs -l ~/.emacs.d/jpablobr/ruby-init.el . &'
alias e-m-aliases='e ~/.mp/bash/aliases'
alias e-m-config='e ~/.mp/bash/config'
alias e-m-init='e ~/.emacs.d/init.el'
alias e-batch-comp='emacs -batch -f batch-byte-compile *.el'
# apt-get
alias sagi='sudo apt-get install'
# Pids IPs
alias pidips='sudo lsof -iTCP -sTCP:LISTEN -P'
# disk usage with human sizes and minimal depth
alias du1='du -h --max-depth=1'
alias fn='find . -name'
# Browse
alias br-f='firefox'
alias br-c='google-chrome '
 # ANSI color chart
alias ansi-chart='for f in {30..37};do for b in {40..47};do printf "\e[%dm\e[%dm%d on %d\e[0m" $b $f $f $b;done;echo;done'
alias hgrep='history | grep $1'
# Grep
alias g-l='la | grep'
alias g-p='ps aux | grep '

##############################################################################->
# - List
alias ls='ls -F --color=auto'
alias lsg='ls -lhGt'
alias lh="ls -lh"
alias lt='ls -lt'
alias la='ls -lah --format=long'
alias l-dir='ls --format=vertical'
alias l-recent='ls -lAt | head'
alias l-old='ls -lAt | tail'
alias ll='/bin/ls -lasi'
alias lll='/bin/ls -saild'
alias lsd='ls -d .[0-9a-zA-Z]*'
lg() { ls -la | grep "$1"; }

##############################################################################->
# - Ruby
alias bu='bundle update'
alias bi='bundle install'
alias dm='rake db:migrate'
# - Rails
alias rac='rails c'
alias rasl='rails s >& log/server-`date +%Y-%m-%d-%H:%M`.log'
alias rag='rails generate'
alias ragr='rails generate resource'
alias ragm='rails generate model'
alias ragc='rails generate controller'
alias rad='rails destroy'
alias radr='rails destroy resource'
alias radc='rails destroy controller'
alias radm='rails destroy model'
alias ratpl='rails -m ~/.rails.d/template.rb'
alias ran='rails new'
alias rad='rails dbconsole'
alias radbm='rake db:migrate'
# - heroku
alias h='heroku'
alias hi='heroku info'
alias hp="git push heroku master"
alias h-l="heroku logs"
alias h-da="heroku domains:add"
alias h-dbp='heroku db:pull'
alias h-add='heroku addons:add'
alias h-cl='heroku config --long'
alias h-c='heroku console'
alias h-t='heroku logs --tail'
# gems
alias gei='gem install'