#!/usr/bin/env bash
# Common aliases
alias o='open . &'
alias more='less'
alias l='less'
alias chx='chmod +x'
alias reload='. ~/.bash_profile'
alias open="gnome-open"
alias cl='clear'
alias _='sudo'
alias k9="kill -9"
alias mk_testd='cd ~/tmp && mkdir whatever && cd whatever'
alias ct='cheat_fu'
alias ctr='cd ~/.cheats_fu && ronn -r *.1.ronn && cd -'
alias srm='sudo rm'
alias rd='rm -rf'
alias r*='rm -fr *'
alias md='mkdir -p'
alias ..='cd ..'
alias g='git'
alias gst='git status'
alias sjp='$SHELL ~/.tmuxinator/jpablobr.tmux'
alias th=thunar
alias disable-touchpad='xinput --set-prop "ImPS/2 ALPS GlidePoint" "Device Enabled" 0'
alias enable-touchpad='xinput --set-prop "ImPS/2 ALPS GlidePoint" "Device Enabled" 1'
alias load-xresources='xrdb -merge ~/.Xresources'
alias ?=man
alias chars='wc -c'
alias hup='kill -HUP \!*'
alias j='jobs -l'
alias lines='wc -l'
alias rehash='hash -r'
alias Rsync='rsync -e ssh -auzv'
alias words='wc -w'
alias z=suspend
alias zombies='ps al | grep " Z "'
alias cpf='cp -fr'

#       |                              action
#   key  +-----------------------------------------+------------------
#        |           gtk_key_theme 'Emacs'         |     Mozilla
# -------+-----------------------------------------+------------------
# CTRL+A | Move cursor to begin of line            | Select all
# CTRL+B | Move cursor backwards one character     | Bookmark manager
# CTRL+C | -->                                     | Copy
# CTRL+D | Delete; delete character under cursor   | --
# CTRL+E | Move cursor to end of line              | Edit page
# CTRL+F | Move cursor forward one character       | Find in this page
# CTRL+G | -->                                     | Find again
# CTRL+H | Backspace                               | History
# CTRL+I | -->                                     | Page info
# CTRL+J | --                                      | --
# CTRL+K | Delete from cursor to end of line       | --
# CTRL+L | -->                                     | Focus location bar
# CTRL+M | -->                                     | New message
# CTRL+N | Next line                               | New navigator window
# CTRL+O | -->                                     | Open file
# CTRL+P | Previous line                           | Print
# CTRL+Q | -->                                     | Quit
# CTRL+R | -->                                     | Reload
# CTRL+S | -->                                     | Save page as
# CTRL+T | -->                                     | New navigator tab
# CTRL+U | Delete from cursor to begin of line     | View source
# CTRL+V | -->                                     | Paste
# CTRL+W | Delete current word until previous word | Close tab
# CTRL+X | -->                                     | Cut
# CTRL+Y | Redo                                    | --
# CTRL+Z | Undo                                    | --
alias gnome-set-emacs-interface='gconftool-2 --set /desktop/gnome/interface/gtk_key_theme Emacs --type string'

# Show history
alias history='fc -l 1'
alias hi='history | tail -20'
alias r='fc -s' # Awesome!
alias whereami='echo "$( hostname --fqdn ) ($(hostname -i)):$( pwd )"'
# Emacs
alias e='emacs -Q -nw'
alias em-s='sudo emacs -Q -nw -l ~/.emacs.d/jpablobr/nw-min.el'
alias emm='emacs -Q -nw -l ~/.emacs.d/jpablobr/nw-min.el'
alias em='emacs -Q -nw -l ~/.emacs.d/jpablobr/nw-jpablobr.el'
alias emr='emacs -Q -nw -l ~/.emacs.d/jpablobr/nw-ruby.el'
alias e-m-aliases='e ~/.mp/bash/aliases'
alias e-m-config='e ~/.mp/bash/config'
alias e-m-init='e ~/.emacs.d/init.el'
alias e-batch-comp='emacs -batch -f batch-byte-compile *.el'
# apt-get
alias sagi='sudo apt-get install'
# Pids IPs
alias pidips='sudo lsof -iTCP -sTCP:LISTEN -P'
# disk usage with human sizes and minimal depth
alias du1='du -h --max-depth=1'
alias fn='find . -name'
# Browse
alias br-f='firefox'
alias br-c='google-chrome '
 # ANSI color chart
alias ansi-chart='for f in {30..37};do for b in {40..47};do printf "\e[%dm\e[%dm%d on %d\e[0m" $b $f $f $b;done;echo;done'
alias hgrep='history | grep $1'
# Grep
alias g-l='la | grep'
alias g-p='ps aux | grep '

##############################################################################->
# - List
alias ls='ls -F --color=auto'
alias lsg='ls -lhGt'
alias lh="ls -lh"
alias lt='ls -lt'
alias la='ls -lah --format=long'
alias l-dir='ls --format=vertical'
alias l-recent='ls -lAt | head'
alias l-old='ls -lAt | tail'
alias ll='/bin/ls -lasi'
alias lll='/bin/ls -saild'
alias lsd='ls -d .[0-9a-zA-Z]*'
lg() { ls -la | grep "$1"; }

##############################################################################->
# - Ruby
alias r-bu='bundle update'
alias r-bi='bundle install'
alias r-rdm='rake db:migrate'
# - Rails
alias ra-c='rails c'
alias ra-sl='rails s >& log/server-`date +%Y-%m-%d-%H:%M`.log'
alias ra-g='rails generate'
alias ra-gr='rails generate resource'
alias ra-gm='rails generate model'
alias ra-gc='rails generate controller'
alias ra-d='rails destroy'
alias ra-dr='rails destroy resource'
alias ra-dc='rails destroy controller'
alias ra-dm='rails destroy model'
alias ra-tpl='rails -m ~/.rails.d/template.rb'
# - heroku
alias h='heroku'
alias h-i='heroku info'
alias h-p="git push heroku master"
alias h-l="heroku logs"
alias h-da="heroku domains:add"
alias h-dbp='heroku db:pull'
alias h-add='heroku addons:add'
alias h-cl='heroku config --long'
alias h-c='heroku console'
alias h-t='heroku logs --tail'
