#!/bin/bash
# ----------------------------------------------------------------------
# - BASH COMPLETION:

test -z "$BASH_COMPLETION" && {
    bash=${BASH_VERSION%.*}; bmajor=${bash%.*}; bminor=${bash#*.}
    test -n "$PS1" && test $bmajor -gt 1 && {
        # search for a bash_completion file to source
        for f in /usr/local/etc/bash_completion \
            /usr/pkg/etc/bash_completion \
            /opt/local/etc/bash_completion \
            /etc/bash_completion
        do
            test -f $f && {
                . $f
                break
            }
        done
    }
    unset bash bmajor bminor
}

: ${USER_BASH_COMPLETION_DIR:=$HOME/bin/completions}

test -n "$USER_BASH_COMPLETION_DIR" && {
  # source completion directory definitions
  if [ -d $USER_BASH_COMPLETION_DIR -a -r $USER_BASH_COMPLETION_DIR -a \
       -x $USER_BASH_COMPLETION_DIR ]; then
    for i in $USER_BASH_COMPLETION_DIR/*; do
      [[ ${i##*/} != @(*~|*.bak|*.swp|\#*\#|*.dpkg*|.rpm*) ]] &&
      [ \( -f $i -o -h $i \) -a -r $i ] && . $i
    done
  fi
  unset i
}
