#!/bin/sh
# ----------------------------------------------------------------------
# - Source functions Dir:

MP_FUNCTIONS_DIR=$HOME/.mp/bash/functions

test -n "$MP_FUNCTIONS_DIR" && {
  if [ -d $MP_FUNCTIONS_DIR ]; then
    for i in $MP_FUNCTIONS_DIR/*; do
      [ ${i##*/} != @(*~|*.bak|*.swp|\#*\#|*.dpkg*|.rpm*) ] &&
      [ \( -f $i -o -h $i \) -a -r $i ] && . $i
    done
  fi
  unset i
}
