#!/bin/bash
# ----------------------------------------------------------------------
# - PATH:

JAVA_HOME=/usr/lib/jvm/java-6-sun/
export JAVA_HOME

# bin
PATH="/bin:/usr/bin:/usr/local/bin:$PATH"
PATH="$JAVA_HOME/bin:$PATH"

# sbin
PATH="/usr/local/sbin:/usr/sbin:/sbin:$PATH"

# if Haskell
test -d "$HOME/.cabal/bin" &&
PATH="$HOME/.cabal/bin:$PATH"

# if node.js.
test -d "$HOME/local/node/bin" &&
PATH="$HOME/local/node/bin:$PATH"

#-----------------------------------------------------------------------
# - if $HOME/bin

if test -d "$HOME/bin"; then
    for b in `find ~/bin/ -type d | cut -c 1-`; do
        PATH="$b:$PATH"
    done
fi