#!/bin/bash
# ----------------------------------------------------------------------
# - PATH:

JAVA_HOME=/usr/lib/jvm/java-6-sun/
export JAVA_HOME
export CLASSPATH=.:/usr/share/java/junit.jar

export CPATH=$CPATH:/usr/include/gtk-2.0
export CPATH=$CPATH:/usr/include/glib-2.0/
export CPATH=$CPATH:/usr/lib/glib-2.0/include/
export CPATH=$CPATH:/usr/include/pango-1.0/
export CPATH=$CPATH:/usr/lib/gtk-2.0/include/
export CPATH=$CPATH:/usr/include/atk-1.0/

# bin
PATH="/bin:/usr/bin:/usr/local/bin:$PATH"
PATH="$JAVA_HOME/bin:$PATH"

# sbin
PATH="/usr/local/sbin:/usr/sbin:/sbin:$PATH"

# if ~/bin.
test -d "$HOME/bin" &&
PATH="$HOME/bin:$PATH"

# if Haskell
test -d "$HOME/.cabal/bin" &&
PATH="$HOME/.cabal/bin:$PATH"

# if node.js.
test -d "$HOME/local/node/bin" &&
PATH="$HOME/local/node/bin:$PATH"