#!/bin/bash
# ----------------------------------------------------------------------
# - PROMP:

RED="\[\033[0;31m\]"
BROWN="\[\033[0;33m\]"
GREY="\[\033[0;97m\]"
GREEN="\[\033[0;32m\]"
BLUE="\[\033[0;34m\]"
PS_CLEAR="\[\033[0m\]"
SCREEN_ESC="\[\033k\033\134\]"

COLOR1="${BLUE}"
COLOR2="${BLUE}"
P="\$"

if [ "$LOGNAME" != "jpablobr" ]; then
    COLOR1="${RED}"
    COLOR2="${BROWN}"
    P="#"
else
    COLOR1="${GREEN}"
    COLOR2="${BROWN}"
    P="\$"
fi

prompt_color() {
    if hostname | grep -q 'dell'; then
       PS1="${COLOR1}\W \h → ${GREY}"
    else
       PS1="${COLOR1}\W \h → ${GREY}"
    fi

    PS2="\[[33;1m\]continue \[[0m[1m\]> "
}

test -n "$PS1" && prompt_color
