#!/bin/bash
#-----------------------------------------------------------------------
# - File to source
# if RVM.
test -s  "$HOME/.rvm/scripts/rvm" &&
source "$HOME/.rvm/scripts/rvm"

# tmuxinator
test -s "$HOME/.tmuxinator/scripts/tmuxinator" &&
source "$HOME/.tmuxinator/scripts/tmuxinator"

# if bashmarks
test -f "$HOME/bin/bashmarks.sh" &&
source "$HOME/bin/bashmarks.sh"

# if BDSM
test -s "/usr/local/bdsm/extensions/builtin/core/modules/shell/project/interactive" &&
source "/usr/local/bdsm/extensions/builtin/core/modules/shell/project/interactive"
