#!/bin/bash
#-----------------------------------------------------------------------
# - File to source

# if bashmarks
test -f "$HOME/bin/sh/bashmarks.sh" &&
source "$HOME/bin/sh/bashmarks.sh"

# if ~/.private
test -f "$HOME/.private/bashrc" &&
source "$HOME/.private/bashrc"

# if RVM.
test -s  "$HOME/.rvm/scripts/rvm" &&
source "$HOME/.rvm/scripts/rvm"

test -s "$HOME/.rvm/contrib/ps1_functions" &&
source "$HOME/.rvm/contrib/ps1_functions"

# tmuxinator
test -s "$HOME/.tmuxinator/scripts/tmuxinator" &&
source "$HOME/.tmuxinator/scripts/tmuxinator"

# Check to make sure that RVM is actually loaded before adding
# the customizations to it.
if [ "$rvm_path" ]
then
    # Load the auto-completion script if RVM was loaded.
    [[ -r $rvm_path/scripts/completion ]] && . $rvm_path/scripts/completion

    switch () {
      rvm $1
      local v=$(rvm_version)
      rvm wrapper $1 $EDITOR
      echo "Switch to Ruby version: "$v
    }

    rvm_default () {
      rvm --default $1
      rvm wrapper $1 $EDITOR
    }

    function rvm_version () {
      ruby --version
    }

fi
