#!/bin/bash
# ----------------------------------------------------------------------
# - SSH

test -f "$HOME/.ssh/environment" &&
export SSH_ENV="$HOME/.ssh/environment"

test -f ~/.ssh/known_hosts && {
    _ssh_hosts() {
        grep "Host " ~/.ssh/config 2> /dev/null | sed -e "s/Host //g"
        # http://news.ycombinator.com/item?id=751220
        cat ~/.ssh/known_hosts | cut -f 1 -d ' ' | sed -e s/,.*//g | uniq | grep -v "\["
    }
    complete -W "$(_ssh_hosts)" ssh
}
